In [1]:
import numpy as np

print(np.__version__)


2.1.3


In [2]:
a = np.array([1, 2, 3, 4, 5])

print(a)
print("shape:", a.shape)
print("dtype:", a.dtype)


[1 2 3 4 5]
shape: (5,)
dtype: int64


In [3]:
# Варіант 2 — Львів

temps = np.array([-3, -2, 2, 8, 13, 16, 18, 17, 13, 8, 3, -1])

days_in_month = np.array([
    31, 28, 31, 30, 31, 30,
    31, 31, 30, 31, 30, 31
])

month_numbers = np.arange(1, 13)

print("Місто: Львів")
print()

print("temps:")
print(temps)
print("shape:", temps.shape)
print("dtype:", temps.dtype)

print()

print("days_in_month:")
print(days_in_month)
print("shape:", days_in_month.shape)
print("dtype:", days_in_month.dtype)

print()

print("month_numbers:")
print(month_numbers)
print("shape:", month_numbers.shape)
print("dtype:", month_numbers.dtype)


Місто: Львів

temps:
[-3 -2  2  8 13 16 18 17 13  8  3 -1]
shape: (12,)
dtype: int64

days_in_month:
[31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,)
dtype: int64

month_numbers:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)
dtype: int64


In [4]:
temps_f = temps * 9 / 5 + 32

print("Температура в °C:")
print(temps)

print()

print("Температура в °F:")
print(temps_f)


Температура в °C:
[-3 -2  2  8 13 16 18 17 13  8  3 -1]

Температура в °F:
[26.6 28.4 35.6 46.4 55.4 60.8 64.4 62.6 55.4 46.4 37.4 30.2]


In [5]:
warm_mask = temps > 15

print("Температура > 15°C:")
print(warm_mask)

warm_days = days_in_month[warm_mask]

print()
print("Кількість днів у теплих місяцях:")
print(warm_days)

print()
print("Всього днів тепліше 15°C:", warm_days.sum())


Температура > 15°C:
[False False False False False  True  True  True False False False False]

Кількість днів у теплих місяцях:
[30 31 31]

Всього днів тепліше 15°C: 92


In [6]:
total_days = days_in_month.sum()

print("Всього днів у році:", total_days)
print("Чи дорівнює 365:", total_days == 365)



Всього днів у році: 365
Чи дорівнює 365: True


In [7]:
warmest_index = temps.argmax()
coldest_index = temps.argmin()

warmest_temp = temps[warmest_index]
coldest_temp = temps[coldest_index]

warmest_month = month_numbers[warmest_index]
coldest_month = month_numbers[coldest_index]

print("Найтепліший місяць:")
print("Номер місяця:", warmest_month)
print("Температура:", warmest_temp, "°C")
print("Індекс:", warmest_index)

print()

print("Найхолодніший місяць:")
print("Номер місяця:", coldest_month)
print("Температура:", coldest_temp, "°C")
print("Індекс:", coldest_index)


Найтепліший місяць:
Номер місяця: 7
Температура: 18 °C
Індекс: 6

Найхолодніший місяць:
Номер місяця: 1
Температура: -3 °C
Індекс: 0


In [8]:
negative_mask = temps < 0

negative_months = month_numbers[negative_mask]

print("Місяці з температурою нижче 0°C:")
print(negative_months)


Місяці з температурою нижче 0°C:
[ 1  2 12]


In [9]:
sorted_temps = np.sort(temps)

print("Температури за зростанням:")
print(sorted_temps)

print()

print("Оригінальний масив temps:")
print(temps)


Температури за зростанням:
[-3 -2 -1  2  3  8  8 13 13 16 17 18]

Оригінальний масив temps:
[-3 -2  2  8 13 16 18 17 13  8  3 -1]


In [10]:
sun_hours = np.array([
    50, 65, 100, 135, 190, 210,
    225, 215, 165, 110, 60, 45
])

print("Сонячні години:")
print(sun_hours)


Сонячні години:
[ 50  65 100 135 190 210 225 215 165 110  60  45]


In [11]:
data = np.array([
    temps,
    days_in_month,
    sun_hours
])

print("data:")
print(data)

print()
print("shape:", data.shape)
print("dtype:", data.dtype)


data:
[[ -3  -2   2   8  13  16  18  17  13   8   3  -1]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 50  65 100 135 190 210 225 215 165 110  60  45]]

shape: (3, 12)
dtype: int64


In [12]:
row_sums = data.sum(axis=1)

print("Сума кожного рядка:")
print(row_sums)


Сума кожного рядка:
[  92  365 1570]


In [13]:
row_means = data.mean(axis=1)

print("Середнє кожного рядка:")
print(row_means)

Середнє кожного рядка:
[  7.66666667  30.41666667 130.83333333]


In [14]:
column_sums = data.sum(axis=0)

print("Сума по кожному стовпцю:")
print(column_sums)


Сума по кожному стовпцю:
[ 78  91 133 173 234 256 274 263 208 149  93  75]


In [15]:
january = data[:, 0]

print("Дані за січень:")
print(january)

print("Сума за січень:", january.sum())


Дані за січень:
[-3 31 50]
Сума за січень: 78


In [16]:
rows = np.array([
    temps,
    days_in_month
])

print("rows:")
print(rows)

print()
print("shape:", rows.shape)


rows:
[[-3 -2  2  8 13 16 18 17 13  8  3 -1]
 [31 28 31 30 31 30 31 31 30 31 30 31]]

shape: (2, 12)


In [17]:
correction = np.array([1, 0])

print("correction:")
print(correction)

print("shape:", correction.shape)


correction:
[1 0]
shape: (2,)


In [18]:
rows + correction


ValueError: operands could not be broadcast together with shapes (2,12) (2,) 

In [19]:
correction_2d = correction.reshape(2, 1)

print("correction після reshape:")
print(correction_2d)

print("shape:", correction_2d.shape)


correction після reshape:
[[1]
 [0]]
shape: (2, 1)


In [20]:
result = rows + correction_2d

print("Результат:")
print(result)

print()
print("shape:", result.shape)


Результат:
[[-2 -1  3  9 14 17 19 18 14  9  4  0]
 [31 28 31 30 31 30 31 31 30 31 30 31]]

shape: (2, 12)


Письмові відповіді
1. Різниця між shape == (12,) і shape == (1, 12)
shape == (12,) означає одновимірний масив із 12 елементів.

shape == (1, 12) означає двовимірний масив з 1 рядком і 12 стовпцями.

Кількість елементів однакова, але структура масивів різна.

2. Чому temps[temps > 15] повертає масив іншої довжини?
temps > 15 створює булеву маску. Для кожного елемента вона визначає, чи температура більша за 15°C.

NumPy вибирає тільки ті елементи, де значення маски дорівнює True.

Для Львова результат:

[16 18 17]

Тому результат має 3 елементи замість 12.

3. Що станеться, якщо додати масив форми (3,) до масиву форми (3, 12)?
Виникне помилка broadcasting.

Форми (3, 12) і (3,) є несумісними, тому що при порівнянні справа наліво розміри 12 і 3 не збігаються і жоден з них не дорівнює 1.

4. Чому rows + correction спочатку дає помилку, а rows + correction.reshape(2, 1) — ні?
rows має форму (2, 12), а correction має форму (2,).

При broadcasting форми порівнюються справа наліво. Числа 12 і 2 несумісні, тому виникає помилка.

Після correction.reshape(2, 1) форма стає (2, 1).

Тепер форми (2, 12) і (2, 1) сумісні: 2 збігається з 2, а 1 може бути розширена до 12.

Тому додавання працює. До всіх елементів першого рядка додається 1, а до всіх елементів другого рядка додається 0.